apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-live-ui
spec:
  template:
    spec:
      containers:
        - name: registration-live-ui
          env:
          - name: ROUTE_HOSTNAME
            value: http://registration-command-seating.apps.cluster-c971.c971.example.opentlc.com/sa/status
