apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-live-ui
spec:
  template:
    spec:
      containers:
        - name: registration-live-ui
          env:
          - name: ROUTE_HOSTNAME
            value: http://registration-command-seating.apps.cluster-eeb9.eeb9.example.opentlc.com/sa/status
          #- name: API_KEY
          #  value: a486f905b59a96e6c4c59d34365290c8
